/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_nc_gs_io_UTF8Util */

#ifndef _Included_com_nc_gs_io_UTF8Util
#define _Included_com_nc_gs_io_UTF8Util

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nc_gs_io_UTF8Util
 * Method:    utf8BytesToArray
 * Signature: ([B[CI)I
 */
JNIEXPORT jint JNICALL Java_com_nc_gs_io_UTF8Util_utf8BytesToArray
  (JNIEnv *, jclass, jbyteArray, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
